### ISSUE TITLE
MaxSecure detects latest release as a Trojan?

### ISSUE THREAD

**Issue by mercuriosa** [Orbmu2k/nvidiaProfileInspector#82] opened 2021-08-10 01:27 UTC
I check on virustotal and there's a detection from MaxSecure, was anybody aware?

**Comment by Chaython** [comment] 2021-08-10 05:57
Ask yourself dafuq is MaxSecure.
A single PUP / FP is not worth looking into especially from a company no one ever heard of.

**Comment by mercuriosa** [comment] 2021-08-10 07:00
> Ask yourself dafuq is MaxSecure.
> A single PUP / FP is not worth looking into especially from a company no one ever heard of.

I never heard of it either and figured it's a false postive, just wanted to bring it to attention just in case

**Comment by Chaython** [comment] 2021-08-10 08:03
Whenever you see a false positive in an open source project and want to help out, contact the security client's customer support. Complain about the false positive and link to this source material. They will either, resolve the false positive, or tell you why they thing it's a pup and will stay that way. They may also find it to actually be malicious, but that's truly a rarity unseen by me.
Kaspersky usually resolved within 48 hours, but crap-ware like whatever dafuq is MaxSecure, may take long or may never even respond. I wish Virus Total had a "consumer" mode, that excluded unreliable AV. Many of the security tools in VT are just rebrands and don't make their own definitions, or even their own GUI, but simply license it all, slap their own spy ware in, their own name and sell it.

**Comment by Orbmu2k** [comment] 2021-08-10 08:10
@mercuriosa 
what version did you check? i can not reproduce your result. i dont even see this vendor in the list.

2.3.0.10: https://www.virustotal.com/gui/url/d1728fae1f2e8904cad95c043c1ad3cd51a0b264575d83fca0297d0476e20530/detection 

2.3.0.13:
https://www.virustotal.com/gui/url/4d6d56b35324a76c56eae9f3aa8555202a8879de1364057b2b4a9dc135b5f4f7/detection

**Closed by Orbmu2k** 2021-08-10 08:10 UTC

**Comment by Chaython** [comment] 2021-08-10 08:17
> 
> 
> @mercuriosa
> what version did you check? i can not reproduce your result. i dont even see this vendor in the list.
> 
> 2.3.0.10: https://www.virustotal.com/gui/url/d1728fae1f2e8904cad95c043c1ad3cd51a0b264575d83fca0297d0476e20530/detection
> 
> 2.3.0.13:
> https://www.virustotal.com/gui/url/4d6d56b35324a76c56eae9f3aa8555202a8879de1364057b2b4a9dc135b5f4f7/detection

Ya seems to be SEO spam to me.

**Comment by mercuriosa** [comment] 2021-08-10 18:27
> @mercuriosa
> what version did you check? i can not reproduce your result. i dont even see this vendor in the list.
> 
> 2.3.0.10: https://www.virustotal.com/gui/url/d1728fae1f2e8904cad95c043c1ad3cd51a0b264575d83fca0297d0476e20530/detection
> 
> 2.3.0.13:
> https://www.virustotal.com/gui/url/4d6d56b35324a76c56eae9f3aa8555202a8879de1364057b2b4a9dc135b5f4f7/detection

It's only detected if you download and upload the zip for some reason, not by the download link
